.TH "Artist.cpp" 3 "Thu Jul 1 2021" "Version v1.0" "2gether - Reliability Assessment Model (RAM)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artist.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Artist\&.h'\fP
.br
\fC#include 'GenericFunc\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2gether - Reliability Assessment Model (RAM) from the source code\&.
