.TH "Artwork.h" 3 "Thu Jul 1 2021" "Version v1.0" "2gether - Reliability Assessment Model (RAM)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artwork.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Rating\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArtwork\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2gether - Reliability Assessment Model (RAM) from the source code\&.
