.TH "Artwork.cpp" 3 "Thu Jul 1 2021" "Version v1.0" "2gether - Reliability Assessment Model (RAM)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artwork.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Artwork\&.h'\fP
.br
\fC#include <cstddef>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2gether - Reliability Assessment Model (RAM) from the source code\&.
