.TH "GenericFunc.h" 3 "Thu Jul 1 2021" "Version v1.0" "2gether - Reliability Assessment Model (RAM)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericFunc.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgnfnc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBgnfnc::getExecutablePath\fP ()"
.br
.ti -1c
.RI "std::string \fBgnfnc::getExecutablePathAndMatchItWithFilename\fP (const std::string &fileName)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2gether - Reliability Assessment Model (RAM) from the source code\&.
