.TH "GenericFunc.cpp" 3 "Thu Jul 1 2021" "Version v1.0" "2gether - Reliability Assessment Model (RAM)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericFunc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'GenericFunc\&.h'\fP
.br
\fC#include 'dirent\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <sstream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2gether - Reliability Assessment Model (RAM) from the source code\&.
