.TH "Rating.cpp" 3 "Thu Jul 1 2021" "Version v1.0" "2gether - Reliability Assessment Model (RAM)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rating.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Rating\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2gether - Reliability Assessment Model (RAM) from the source code\&.
